# The CA Gateway presents when it decrypts HTTPS.
#
# Inspection cannot be turned on without one. A PUT to the account's Gateway
# configuration carrying tls_decrypt.enabled = true against an account with no
# active certificate is rejected outright:
#
#   400 code 2211 "TLS decryption cannot be enabled without a certificate."
#
# Cloudflare does not provision this the way it provisions the configuration
# object - a Zero Trust account starts with no certificate at all, and the
# managed root has to be generated and then activated before the edge will use
# it. That is what this resource does: generation and activation in one, with
# the resulting ID fed into settings.certificate by locals.settings.tf, so the
# configuration write depends on the certificate and cannot run in front of it.
#
# Leaving var.inspection_certificate null is the right choice on an account
# whose CA is already active - generated by hand, or a customer root uploaded
# out of band - in which case name it with settings.certificate.id instead.
#
# THE DEVICE SIDE IS NOT HERE. Activating a CA at the edge is half of it; every
# device on WARP has to trust the same root or every HTTPS site returns a
# certificate error. The WARP client installs Cloudflare's managed root on a
# managed deployment and an unmanaged device gets nothing, so the certificate
# output below exists to be handed to whatever distributes it. Activation on its
# own changes nothing for users until inspection is switched on, which is the
# safe order and the reason these are two separate settings.
resource "cloudflare_zero_trust_gateway_certificate" "this" {
  for_each = var.inspection_certificate == null ? toset([]) : toset([var.account_id])

  account_id           = each.key
  validity_period_days = var.inspection_certificate.validity_period_days

  # Generated but inactive is a certificate the edge will not present, and so an
  # account that still cannot decrypt. There is no case for creating one here
  # and leaving it dormant.
  activate = true

  lifecycle {
    # Two answers to "which CA does Gateway present" and no way to tell which
    # one the account is actually running on. The generated certificate would be
    # activated and the configuration would then name the other one.
    precondition {
      condition     = try(var.settings.certificate.id, null) == null
      error_message = "inspection_certificate generates and activates a CA while settings.certificate.id names an existing one. Pick one: drop settings.certificate.id to let this module own the certificate, or set inspection_certificate = null and keep pointing at the certificate that is already there."
    }

    # validity_period_days is fixed at creation, so changing it replaces the
    # certificate - a new root, which every device has to trust before it is
    # presented. Create-before-destroy so the replacement is generated and
    # activated, then the configuration is repointed at it, and only then is the
    # old one removed; the reverse order would leave the account briefly with no
    # active CA while inspection is on, which is every HTTPS request failing.
    create_before_destroy = true
  }
}
